### ISSUE TITLE
Cannot install -r requirements.txt

### ISSUE THREAD

**Issue by smile-II** [OSU-NLP-Group/QA4RE#4]
INFO: pip is looking at multiple versions of transformers to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r /raid/QA4RE/requirements.txt (line 14), -r /raid/QA4RE/requirements.txt (line 99) and huggingface-hub==0.6.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested huggingface-hub==0.6.0
    datasets 2.2.2 depends on huggingface-hub<1.0.0 and >=0.1.0
    transformers 4.30.0 depends on huggingface-hub<1.0 and >=0.14.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by smile-II** [comment]
"Could you please verify the installation environment? Are these Python packages compatible?"

**Comment by drogozhang** [comment]
Hi,

Thanks for bring up this issue, I made the pip install packages more lightweight by only keeping several important ones and the rest will be installed automatically. Also, I provided more specific python version for less inconsistency and fixed a typo in QA4RE LLM code.

So please re gitclone and follow the new instructions which are successfully verified twice on my side.

Please let me know if you have any other issues using the new instruction.

**Comment by smile-II** [comment]
Thank you for your modifications！ I have successfully run your project！
